### ISSUE TITLE
About the language code

### ISSUE THREAD

**Issue by yfdyh000** [Rem0o/FanControl.i18n#1]
ISO 639 is not enough, for users of Chinese characters, at least zh-CN and zh-TW are needed (https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2). You may need to determine the language code format, as it has other forms of representation.

**Comment by yfdyh000** [comment]
By the way, I'm worried about potential PR conflicts since this is not a translation platform based strings and there are no placeholder lock.

**Comment by Rem0o** [comment]
You are right.  I linked the wrong language tag link.  

Windows uses a combination of 639 and 3166 for the country code as a suffix.

https://en.wikipedia.org/wiki/IETF_language_tag  should probably be the right link?

**Comment by Rem0o** [comment]
> By the way, I'm worried about potential PR conflicts since this is not a translation platform based strings and there are no placeholder lock. 

Could you elaborate with an example?

**Comment by yfdyh000** [comment]
> > By the way, I'm worried about potential PR conflicts since this is not a translation platform based strings and there are no placeholder lock.
> 
> Could you elaborate with an example?

https://github.com/Rem0o/FanControl.i18n/pull/6 is a good example, but it's not mandatory.
