### ISSUE TITLE
How to change language?

### ISSUE THREAD

**Issue by HardyDan** [Rem0o/FanControl.i18n#16]
Where should I put the i18n file? I tried to putting the i18n file into zh-CN floder and then changing the culture to zh-CN, but it didn't work, nothing changed. Please guide me, thanks!

**Comment by Rem0o** [comment]
This need to be compiled into the software.  It will go with the next release.

**Comment by HardyDan** [comment]
> This need to be compiled into the software. It will go with the next release.

Okey, thanks for your help. Can I know what time publish next release? How many days will it take?

**Comment by Rem0o** [comment]
I can't guarantee you a time frame. Most likely in a week or two.
