### ISSUE TITLE
Unusual small space for translation

### ISSUE THREAD

**Issue by SkiffPL** [Rem0o/FanControl.i18n#19]
Hi. I've found some places in "Settings" submenu where space for translation is unusually small, but there is much more free space for those strings. See attached image.

One of this is sidebar with "main/theme/tray (and so on)".
For polish language simply there is no alternative to word "Ustawienia" (Settings). If it would be possible to extend this sidebar for this word - I would be able to change or abbreviate the rest of them
![fan](https://github.com/user-attachments/assets/d615cd83-a563-4f4e-883a-aa6bdddd57bb)

**Comment by vagman** [comment]
For Greek the translation is "Ρυθμίσεις" but it can be cut down to "Ρυθμ.", you should have something similar in Polish. Even better solution: ommit the plural and use the equivalent of Setting which is "Ρύθμιση" in Greek and fits exactly the 7 character placehgolder.

**Comment by SkiffPL** [comment]
> I will increase both the plugin label and the symbol, but the left-side bar I really want to keep it squared. Isn't there an abbreviation or anything that could fit in there?

OK if it is really a problem then I'll use abbreviation for settings translation (it will be ugly, but better than two line word). Thanks!

@vagman I've tried to avoid abbreviation.
