### ISSUE TITLE
Update V203 translation issues

### ISSUE THREAD

**Issue by Cantejito** [Rem0o/FanControl.i18n#21]
**Tooltip don't get translated**

Spanish translation
![Screenshot_1](https://github.com/user-attachments/assets/15971435-a8b4-411d-98cd-d4839b52b262)

Italian translation
![Screenshot_2](https://github.com/user-attachments/assets/695f5bf7-74da-498a-9f83-209ebce3d0f8)

---

**If you disable the translation, some parts of the interface will stay translated.**

![Desktop Screenshot 2024 09 19 - 17 49 02 82](https://github.com/user-attachments/assets/076b7b7d-4335-44aa-8ddb-9b154d698df1)

---

**Tested on two completly different PCs, both just updated to V203.**

**Comment by Rem0o** [comment]
The two two tooltips I forgot to change. 
As for the + sign menu this will be fixed in the next release also.

**Comment by Cantejito** [comment]
Buenas @JoseArtunedo, por ahora soy yo el voluntario para traducirlo al español.

Te aclaro algunos puntos:
• No, no he usado el traductor de Google para hacer la traducción.
• La primera versión la hice en un rato que tenía libre, así que algunas cosas las traduje sin calentarme mucho la cabeza a modo de placeholder para que saliesen con la siguiente versión.
• Hay cosas que no sé cómo quedarán en la interfaz hasta que Rémi no lo compile y lance la actualización, de las cuales ya he cambiado algunas en las revisiones.
• Algunas cosas que has puntuado en la imagen son cambios completamente subjetivos.

**Comment by vagman** [comment]
I don't weather it is related to the issue above or not but one Greek translation isn't fetched by the app:
![Screenshot 2024-09-20 192146](https://github.com/user-attachments/assets/7c0ec002-7dd9-4c82-a860-f4ae192d0914)

**Comment by Rem0o** [comment]
See V204
