### ISSUE TITLE
Untranslated trings

### ISSUE THREAD

**Issue by Caio99BR** [Rem0o/FanControl.i18n#42]
I think some of the strings are here but it's not showing on app: https://github.com/Rem0o/FanControl.i18n/blob/main/Parameters/Parameters.pt-BR.json#L4
("Add sensor" is nowhere to be found)

![image](https://github.com/user-attachments/assets/56a8c6e3-4a66-4a9d-8e71-8de4521b8ed3)

**Comment by Rem0o** [comment]
This one slipped by.   Will be added.

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.i18n/commit/d7b7a31458aedc33cdd0d6d300e565d8325d187e
