### ISSUE TITLE
Question about the translations

### ISSUE THREAD

**Issue by malloc2k** [Rem0o/FanControl.i18n#48]
Hey Remo, I wanted to know how much time do the translations take to be implemented on the main release of FanControl after a successful commit. 

Thanks :D

**Comment by Rem0o** [comment]
There is no set schedule.  I don't plan versions with the translations.   They just get bundled in with the next version whenever that is ready.  Can't get you a clearer answer, as there is no version in progress at the moment.

**Comment by malloc2k** [comment]
Alright, thanks! Wanted to know to text out how the translations set on the actual app and make some changes if needed :P 

Great work on the app tho, thanks so much for this :)
